### ISSUE TITLE
Files in workspace could not be opened!

### ISSUE THREAD

**Issue by pashkulev** [eclipse/dirigible#460] opened 2019-11-05 11:41 UTC
While running Dirigible in Docker, the files from the workspace stopped opening in the editor.
If you hit this issue, what you can try to do is click on the Themes dropdown menu in the upper right area and select Reset. 

 - OS: WIndows 10
 - Browser: chrome

**Comment by delchev** [comment] 2019-12-07 15:50
Thanks @pashkulev for giving an option for solving the issue. If you can give more info how to reproduce this to be able to understand the root cause better, we can fix it, otherwise, I would close this issue for now.

**Closed by delchev** 2019-12-07 15:50 UTC
Labels: bug, component-ide, priority-low, usability, web-ide
