### ISSUE TITLE
[ORM] Sort and Order does not work

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#352] opened 2018-10-09 08:32 UTC
Sort and Order does not work e.g.:
../api/Products/Reviews.js?$sort=CreatedAt&$order=desc
../api/Products/Reviews.js?sort=CreatedAt&order=desc

**Comment by shturec** [comment] 2019-03-28 15:04
The `sort` parameter does not work again but for a different reason and it's a potentially system-wide issue this time.
The issue is that the `split` function is missing for String objects. I noted it wrt [sort](https://github.com/dirigiblelabs/api-v3-db/blob/master/db/v3/ormstatements.js#L153) in daos using the default js engine, but it should be a general problem anywhere it is used. Seems to be a regression introduced by the upgrade of rhino.

019-03-27 12:25:24,122 INFO [http-nio-8080-exec-6] a.d.d.zeus_applications_html5 [LogFacade.java:125] Listing **************** entity collection with list operators:  $limit[10], $offset[0], $order[asc], $sort[name]
2019-03-27 12:25:24,124 ERROR [http-nio-8080-exec-6] a.h.r.d.service [LogFacade.java:129] Serving resource[], Verb[GET], Content-Type[[]], Accept[application/json,text/plain,*/*] finished in error
org.eclipse.dirigible.api.v3.log.JSServiceException: Cannot find function split in object name.
	at ?.anonymous(db/v3/ormstatements.js:153) ~[na:na]
	at ?.anonymous(db/v3/dao.js:712) ~[na:na]
	at ?.anonymous(http/v3/rs-data.js:410) ~[na:na]
	at ?.anonymous(http/v3/rs.js:829) ~[na:na]
	at ?.?(zeus-applications-html5/api/applications.js:25) ~[na:na]

**Comment by ThuF** [comment] 2020-06-16 12:14
Fixed with the GraalJS (GraalVM) integration and configuration as default engine: https://github.com/eclipse/dirigible/issues/528

**Closed by ThuF** 2020-06-16 12:14 UTC
Labels: bug, component-database, javascript
