### ISSUE TITLE
Error on start 4.0.0

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#491] opened 2019-12-18 09:30 UTC
**Describe the bug**
When starting the Dirigible (Standalone) it fills the console with errors.

**To Reproduce**
Start latest standalone dirigible and open the console of the browser.

**Expected behavior**
no errors, or, at most, some warnings

**Screenshots**
<img width="1274" alt="dirigible_errors" src="https://user-images.githubusercontent.com/1436515/71073786-b0488400-2189-11ea-8c3b-b55e0d1b80f4.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version latest

**Additional context**
I am attaching a text file with the errors.
[console-export-2019-12-18_11-26-32.txt](https://github.com/eclipse/dirigible/files/3977613/console-export-2019-12-18_11-26-32.txt)

**Comment by g051051** [comment] 2020-11-29 00:34
Is this still an issue with 5.x?

**Comment by ThuF** [comment] 2020-11-29 07:41
@g051051 I'm not able to re-produce these errors anymore. It seems that they were fixed over time along with other issues. I've just fixed one small issue, with console error from the Welcome page (https://github.com/eclipse/dirigible/issues/662). @g051051 can you double check on your side, so we could close this issue?

**Comment by g051051** [comment] 2020-11-29 14:00
@ThuF I don't see the problem listed in #662, but I do see the other ones related to font errors.  According to https://stackoverflow.com/questions/55868995/ots-parsing-error-failed-to-convert-woff-2-0-font-to-sfnt-for-font-files-of-gly this is due to the fonts being corrupted during the build process.
![console_errors](https://user-images.githubusercontent.com/2124974/100544078-4baef980-3221-11eb-8e6e-3fa1eebea151.png)

**Comment by ThuF** [comment] 2020-11-29 15:15
@g051051 thanks for noticing that also!

I've created a separate issue to track the process there: https://github.com/eclipse/dirigible/issues/663

It seems that the fix should be relatively simple one:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <configuration>
        <nonFilteredFileExtensions>
            <nonFilteredFileExtension>ttf</nonFilteredFileExtension>
            <nonFilteredFileExtension>woff</nonFilteredFileExtension>
            <nonFilteredFileExtension>woff2</nonFilteredFileExtension>
            <nonFilteredFileExtension>eot</nonFilteredFileExtension>
            <nonFilteredFileExtension>svg</nonFilteredFileExtension>
        </nonFilteredFileExtensions>
    </configuration>
</plugin>
```

**Comment by ThuF** [comment] 2020-11-29 15:17
Closing this issue, as it is no longer reproducible.

**Comment by g051051** [comment] 2020-11-29 15:18
I did try that, but it didn't work.  I'm not familiar enough with the project to know the right place to put that.  In addition, I tried extracting the font file from the packed jars and comparing them against the original file in the project, and it showed them as the same, so it might be that the font is corrupted before it's packaged.

**Closed by ThuF** 2020-11-29 15:17 UTC

**Comment by ThuF** [comment] 2020-11-29 15:27
Thanks @g051051, we can continue to discussion at: https://github.com/eclipse/dirigible/issues/663
