### ISSUE TITLE
[IDE Git] Unable to pull changes from origin

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1630] opened 2022-02-23 14:23 UTC
Issue cloned from https://github.com/SAP/xsk/issues/1323

**Describe the bug**

When you go to the Git perspective and try to pull the latest changes for all repositories, it will fail with an empty error popup. From the console, the only error is Error: $rootScope:inprog Action Already In Progress and $digest already in progress.

**To Reproduce**

Go to the Git perspective
Click on any repository
Click on pull changes
Enter your username and password
See error
Expected behavior

Git pull should pull all the latest changes.

**Desktop:**

OS: macOS 11.4
Browser: Firefox 89
Version: Dirigible 5.11.1

**Comment by vmutafov** [comment] 2022-03-08 13:34
@ThuF could you close this as duplicate of https://github.com/eclipse/dirigible/issues/890 which is already fixed

**Comment by ThuF** [comment] 2022-03-08 14:12
Fixed

**Closed by ThuF** 2022-03-08 14:12 UTC
Labels: bug, component-ide, web-ide, IDE
